---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars_files:
    - vars/db_credentials.yml
    - vars/open-zaak.yml
    - vars/open-notificaties.yml
    # - vars/nlx.yml

  collections:
    - openzaak.deploy

  roles:
    - role: open_zaak_k8s
      vars:  # these override vars_files
        openzaak_version: '1.0.1'
        openzaak_db_host: "{{ db.privateIp }}"
        openzaak_db_port: "{{ db.port }}"
      tags:
        - openzaak

    - role: open_notificaties_k8s
      vars:
        opennotificaties_db_host: "{{ db.privateIp }}"
        opennotificaties_db_port: "{{ db.port }}"
      tags:
        - opennotificaties

    - role: nlx
      vars:
        nlx_instance: test
        nlx_inway_self_address: inway.openzaak.nl
        nlx_inway_services:
          - name: openzaak-zaken
            endpoint_url: https://{{ openzaak_domain }}/zaken/api/v1
            documentation_url: https://open-zaak.readthedocs.org
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/zaken/api/v1/schema/openapi.yaml

          - name: openzaak-documenten
            endpoint_url: https://{{ openzaak_domain }}/documenten/api/v1
            documentation_url: https://open-zaak.readthedocs.org
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/documenten/api/v1/schema/openapi.yaml

          - name: openzaak-catalogi
            endpoint_url: https://{{ openzaak_domain }}/catalogi/api/v1
            documentation_url: https://open-zaak.readthedocs.org
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/catalogi/api/v1/schema/openapi.yaml

          - name: openzaak-besluiten
            endpoint_url: https://{{ openzaak_domain }}/besluiten/api/v1
            documentation_url: https://open-zaak.readthedocs.org
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/besluiten/api/v1/schema/openapi.yaml

          - name: openzaak-autorisaties
            endpoint_url: https://{{ openzaak_domain }}/autorisaties/api/v1
            documentation_url: https://open-zaak.readthedocs.org
            authorization_model: none
            api_specification_document_url: https://{{ openzaak_domain }}/autorisaties/api/v1/schema/openapi.yaml
      tags:
        - nlx
